### ISSUE TITLE
Adding React Hooks rules

### ISSUE THREAD

**Issue by liegeandlief** [feross/eslint-config-standard-react#65] opened 2020-02-10 11:47 UTC
Hey there, is it still the plan to add the React Hooks rules to Standard as discussed in https://github.com/standard/eslint-config-standard-react/pull/63? This would be super useful. Thanks :)

**Comment by feross** [comment] 2020-11-05 00:36
Yes, still planned in a future version of `standard`.

**Comment by feross** [comment] 2020-11-19 05:03
Duplicate of https://github.com/standard/eslint-config-standard-react/issues/57

**Closed as completed by feross** 2020-11-19 05:03 UTC
